// Generated by CoffeeScript 1.8.0
(function() {
  var sections;

  sections = angular.module("interactiveLecture.sections", []);

  sections.config([
    "$stateProvider", "$urlRouterProvider", function($stateProvider, $urlRouterProvider) {
      $stateProvider.state("sections", {
        abstract: true,
        url: "/courses/:courseId/chapters/:chapterId/sections/:sectionId",
        template: "<ui-view></ui-view>",
        resolve: {
          courseId: [
            '$stateParams', function($stateParams) {
              return $stateParams.courseId;
            }
          ],
          chapterId: [
            '$stateParams', function($stateParams) {
              return $stateParams.chapterId;
            }
          ],
          sectionId: [
            '$stateParams', function($stateParams) {
              return $stateParams.sectionId;
            }
          ]
        }
      });
      return $stateProvider.state("sections.lecture", {
        abstract: true,
        url: "/lecture",
        templateUrl: 'sections/courses.details.html'
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=sections.js.map
