// Generated by CoffeeScript 1.8.0
(function() {
  var Hugo, a;

  Hugo = (function() {
    function Hugo() {
      this.blubb = function() {
        return console.log("blubb");
      };
    }

    Hugo.prototype.foobar = function() {
      return console.log("baz");
    };

    return Hugo;

  })();

  a = new Hugo();

  a.blubb();

  a.blubb = function() {
    return console.log("foo");
  };

  a.blubb();

  a.foobar();

  a.foobar = function() {
    return console.log("hurts");
  };

  a.foobar();

}).call(this);

//# sourceMappingURL=test.js.map
