// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var CodeAreaMainCtrl, app;

  app = angular.module("interactiveLecture.codeArea", ['ui.ace', 'ui.bootstrap', "interactiveLecture.codeArea.controllers"]);

  app.directive("codeArea", function() {
    return {
      restrict: "E",
      templateUrl: "/codearea.html",
      require: ["tabController"],
      scope: {
        tabController: '@'
      },
      controller: CodeAreaMainCtrl,
      controllerAs: 'codeAreaMainCtrl'
    };
  });

  CodeAreaMainCtrl = [
    "$scope", "$timeout", "$injector", "$controller", "$modal", function($scope, $timeout, $injector, $controller, $modal) {
      this.addTab = function() {
        return this.tabs.push({
          title: "Neue Klasse",
          active: true,
          focus: true,
          editing: false
        });
      };
      this.tabs = [
        {
          title: "Neue Klasse",
          active: true
        }
      ];
      $scope.tabCtrl = $controller($scope.tabController, {
        $scope: $scope.$new()
      });
      return this.removeTab = function($index, event) {
        var modalInstance;
        event.preventDefault();
        modalInstance = $modal.open({
          templateUrl: '/delete-modal-template.html',
          controller: 'DeleteModalController',
          size: "sm"
        });
        return modalInstance.result.then((function(_this) {
          return function(closeResult) {
            if (closeResult === 'ok') {
              _this.tabs[$index].editor.destroy();
              return _this.tabs.splice($index, 1);
            }
          };
        })(this));
      };
    }
  ];

  app.controller("DeleteModalController", [
    "$scope", "$modalInstance", function($scope, $modalInstance) {
      $scope.ok = function() {
        return $modalInstance.close("ok");
      };
      return $scope.cancel = function() {
        return $modalInstance.dismiss('cancel');
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=codearea.js.map
