// Generated by CoffeeScript 1.8.0
(function() {
  var AppFacade, CompileService, java,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  java = require("java");

  java.classpath.push("/Users/renerichter/NetBeansProjects/Java-Runtime-Compiler/JavaExecutionService/target/JavaExecutionService-1.0-SNAPSHOT-jar-with-dependencies.jar");

  AppFacade = java["import"]("com.lecture.app.AppFacade");

  CompileService = (function() {
    function CompileService(exerciseId) {
      this.startTests = __bind(this.startTests, this);
      this.compileTests = __bind(this.compileTests, this);
      this.compileExercises = __bind(this.compileExercises, this);
      this.facade = new AppFacade(exerciseId);
    }

    CompileService.prototype.compileExercises = function(sourceCode, callback) {
      return this.facade.compileSourceForErrorJson(sourceCode, AppFacade.Scope.EXERCISE, function(err, compilationResult) {
        return callback(compilationResult);
      });
    };

    CompileService.prototype.compileTests = function(sourceCode, callback) {
      return this.facade.compileSourceForErrorJson(sourceCode, AppFacade.Scope.TEST(function(err, compilationResult) {
        return callback(compilationResult);
      }));
    };

    CompileService.prototype.startTests = function(callback) {
      return this.facade.executeTestsForFailureJson(function(err, failures) {
        return callback(failures);
      });
    };

    return CompileService;

  })();

  module.exports = CompileService;

}).call(this);

//# sourceMappingURL=compile_service.js.map
