// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(router) {
    console.log("inside module");
    router.get("/results", function(req, resp) {
      var id;
      id = req.params.id;
      return console.log("GET: " + req.originalUrl);
    });
    return router.post("/", function(req, resp) {
      var id;
      id = req.params.id;
      return console.log("POST: " + id);
    });
  };

}).call(this);

//# sourceMappingURL=test_module.js.map
