// Generated by CoffeeScript 1.8.0
(function() {
  var LocalEndpointService, endpointService;

  endpointService = angular.module("interactiveLecture.codeArea.endPointServices");

  LocalEndpointService = (function() {
    function LocalEndpointService() {}

    return LocalEndpointService;

  })();

  endpointService.service("localEndpointService");

}).call(this);

//# sourceMappingURL=local_endpoint.js.map
