// Generated by CoffeeScript 1.8.0
(function() {
  var JavaController;

  JavaController = (function() {
    function JavaController(socketEndpointService) {
      this.socketEndpointService = socketEndpointService;
    }

    JavaController.prototype.editTab = function() {};

    JavaController.prototype.doneEditing = function() {};

    JavaController.prototype.setTab = function(tab) {
      this.tab = tab;
      return this.tab.setOnChangeListener((function(_this) {
        return function(e) {
          var className, codeObject, data, matches;
          data = e[0].data;
          if (data.action === "insertText" || data.action === "removeText") {
            codeObject = {
              id: tab.id,
              code: tab.content
            };
            _this.socketEndpointService.input(codeObject, 1000);
            matches = /(.*?)(?=\s+|$|extends|implements|\{)/m.exec(tab.content.replace(/([\n\r\s]*(public)+(\s|$)*)?(class|interface|@interface|enum)(\s|$)*/, ''));
            className = /[a-z\W\d_]/.test(matches[0][0]) ? "unbekannte Klasse" : "" + matches[0] + ".java";
            return _this.tab.title = className;
          }
        };
      })(this));
    };

    return JavaController;

  })();

  angular.module("interactiveLecture.codeArea.controllers", ["interactiveLecture.codeArea.endPointServices"]).controller("JavaController", ["socketEndpointService", JavaController]);

}).call(this);

//# sourceMappingURL=code_area_controllers.js.map
