// Generated by CoffeeScript 1.8.0
(function() {
  var lectures;

  lectures = angular.module("interactiveLecture.lectures", []);

  lectures.config([
    "$stateProvider", "$urlRouterProvider", function($stateProvider, $urlRouterProvider) {
      $stateProvider.state("lecture", {
        abstract: true,
        url: "/courses/:courseId/chapters/:chapterId/sections/:sectionId/lecture",
        template: "<ui-view></ui-view>",
        resolve: {
          courseId: [
            '$stateParams', function($stateParams) {
              return $stateParams.courseId;
            }
          ],
          chapterId: [
            '$stateParams', function($stateParams) {
              return $stateParams.chapterId;
            }
          ],
          sectionId: [
            '$stateParams', function($stateParams) {
              return $stateParams.sectionId;
            }
          ]
        }
      });
      $stateProvider.state("lecture.text", {
        abstract: true,
        url: "/text",
        templateUrl: "lecture/lecture.text.html"
      });
      return $stateProvider.state("lecture.video", {
        abstract: true,
        url: "/text",
        templateUrl: "lecture/lecture.video.html"
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=lecture.js.map
