// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var app;

  app = angular.module('interactiveLecture', ['interactiveLecture.codeArea', "ui.router", "interactiveLecture.courses", "interactiveLecture.chapters", "interactiveLecture.exercise", "interactiveLecture.lectures"]);

}).call(this);

//# sourceMappingURL=app.js.map
