// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var app;

  app = angular.module('interactiveLecture', ['interactiveLecture.codeArea', "ui.router"]);

  app.config([
    "$stateProvider", "$urlRouterProvider", function($stateProvider, $urlRouterProvider) {
      $stateProvider.state("courses", {
        url: "/courses",
        templateUrl: 'courses/courses.html'
      });
      return $stateProvider.state("courses.detail", {
        url: "/:courseId",
        templateUrl: 'courses/courses.details.html'
      });

      /*$stateProvider.state "courses.detail",{
        url: "/courses/:courseId",
        templateUrl: 'courses/courses.details.html'
      }
       */
    }
  ]);

}).call(this);

//# sourceMappingURL=app.js.map
