// Generated by CoffeeScript 1.8.0
(function() {
  var chapters;

  chapters = angular.module("interactiveLecture.chapters", []);

  chapters.config([
    "$stateProvider", "$urlRouterProvider", function($stateProvider, $urlRouterProvider) {
      $stateProvider.state("chapters", {
        url: "users/courses/:courseId/chapters",
        templateUrl: 'users/chapters/chapters.html'
      });
      return $stateProvider.state("chapters.detail", {
        url: "/:chapterId",
        templateUrl: 'users/chapters/chapters.details.html'
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=chapters.js.map
