// Generated by CoffeeScript 1.8.0
(function() {
  var ExerciseCodeController, ExerciseController, exercise;

  exercise = angular.module("interactiveLecture.exercise", []);

  ExerciseController = (function() {
    function ExerciseController(scope) {
      this.scope = scope;
      this.scope.hasErrors = false;
      this.scope.$on("errors", (function(_this) {
        return function(data) {
          console.log("got error event");
          _this.scope.hasErrors = true;
          return _this.scope.$apply();
        };
      })(this));
      this.scope.$on("no-errors", (function(_this) {
        return function(data) {
          console.log("got no-error event");
          _this.scope.hasErrors = false;
          return _this.scope.$apply();
        };
      })(this));
    }

    return ExerciseController;

  })();

  ExerciseCodeController = (function() {
    function ExerciseCodeController($scope, $stateParams, courseId, chapterId, sectionId, exerciseId) {
      $scope.language = $stateParams.language;
      $scope.courseId = courseId;
      $scope.chapterId = chapterId;
      $scope.sectionId = sectionId;
      $scope.exerciseId = exerciseId;
    }

    return ExerciseCodeController;

  })();

  exercise.config([
    "$stateProvider", "$urlRouterProvider", function($stateProvider, $urlRouterProvider) {
      $stateProvider.state("exercise", {
        abstract: true,
        url: "users/courses/:courseId/chapters/:chapterId/sections/:sectionId/exercise/:exerciseId",
        templateUrl: "users/exercise/exercise.html",
        resolve: {
          courseId: [
            '$stateParams', function($stateParams) {
              return $stateParams.courseId;
            }
          ],
          chapterId: [
            '$stateParams', function($stateParams) {
              return $stateParams.chapterId;
            }
          ],
          sectionId: [
            '$stateParams', function($stateParams) {
              return $stateParams.sectionId;
            }
          ],
          exerciseId: [
            '$stateParams', function($stateParams) {
              return $stateParams.exerciseId;
            }
          ]
        },
        controller: ["$scope", ExerciseController]
      });
      return $stateProvider.state("exercise.code", {
        url: "/code/:language",
        templateUrl: "users/exercise/exercise.code.html",
        controller: ["$scope", "$stateParams", "courseId", "chapterId", "sectionId", "exerciseId", ExerciseCodeController]
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=exercise.js.map
